import { SDKConfig } from './config';
import { Plugin } from './types';
export declare class WebSDK {
    config: SDKConfig;
    private logger;
    private anonymousId;
    private loginId;
    private commonProperties;
    private dynamicProperties;
    private plugins;
    private identities;
    private queue;
    private processing;
    constructor();
    init(config: Partial<SDKConfig>): void;
    quick(command: string, ...args: any[]): void;
    use(plugin: Plugin): void;
    registerCommonProperties(props: Record<string, any>): void;
    registerPage(props: Record<string, any>): void;
    clearCommonProperties(): void;
    login(userId: string): void;
    identify(id: string): void;
    logout(): void;
    bind(key: string, value: string): void;
    unbind(key: string, value: string): void;
    resetAnonymousIdentity(id?: string): void;
    setProfile(properties: Record<string, any>): void;
    setProfileOnce(properties: Record<string, any>): void;
    incrementProfile(properties: Record<string, number> | string): void;
    appendProfile(properties: Record<string, any[] | any>): void;
    deleteProfile(): void;
    unsetProfile(properties: string[] | string): void;
    trackHeatMap(element: HTMLElement, properties?: Record<string, any>): void;
    trackAllHeatMap(element: HTMLElement, properties?: Record<string, any>): void;
    private buildClickProperties;
    private getElementContent;
    private getSelector;
    track(eventName: string, properties?: Record<string, any>, type?: string): void;
    getPresetProperties(): Record<string, any>;
    private send;
    private flush;
    private isSLSConfigValid;
    private buildSLSUrl;
    private toQuery;
    private sendSLS;
    private sendAjax;
    private storeSet;
    private storeRemove;
    private getRootDomain;
    private parseSourceAttribution;
    private applyStringLimit;
}
export declare const sdk: WebSDK;
